// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class AnyDataType_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.AnyDataType); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.AnyDataType(null);
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.AnyDataType[] AnyDataTypeArray = null;
				if (InstanceType.IsArray())
					AnyDataTypeArray = (VisualScriptTool.Language.AnyDataType[])Instance;
				else
					AnyDataTypeArray = ((System.Collections.Generic.List<VisualScriptTool.Language.AnyDataType>)Instance).ToArray();
				for (int i = 0; i < AnyDataTypeArray.Length; ++i)
				{
					VisualScriptTool.Language.AnyDataType element = AnyDataTypeArray[i];
					ISerializeObject elementObject = AddObject(Array); 
					System.Type elementType = element.GetType();
					Set(elementObject, 1, elementType.AssemblyQualifiedName);
					GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.AnyDataType AnyDataType = (VisualScriptTool.Language.AnyDataType)Instance;
				// Value
				Set(Object, 0, AnyDataType.Value, "Value");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.AnyDataType[] AnyDataTypeArray = (VisualScriptTool.Language.AnyDataType[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					AnyDataTypeArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.AnyDataType>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)AnyDataTypeArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.AnyDataType AnyDataType = (VisualScriptTool.Language.AnyDataType)CreateInstance();
				// Value
				AnyDataType.Value = Get<System.Object>(Object, 0, null);
				returnValue = (T)(object)AnyDataType;
			}
			return returnValue;
		}

	}
}
#endif