// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class ControlStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Control.ControlStatement); }
		}

		public override object CreateInstance()
		{
			return null;
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.ControlStatement[] ControlStatementArray = null;
				if (InstanceType.IsArray())
					ControlStatementArray = (VisualScriptTool.Language.Statements.Control.ControlStatement[])Instance;
				else
					ControlStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Control.ControlStatement>)Instance).ToArray();
				for (int i = 0; i < ControlStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Control.ControlStatement element = ControlStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.ControlStatement ControlStatement = (VisualScriptTool.Language.Statements.Control.ControlStatement)Instance;
				// CompleteStatement
				if (ControlStatement.CompleteStatement == null)
					Set<object>(Object, 1, null, "CompleteStatement");
				else
				{
					ISerializeObject CompleteStatementObject = AddObject(Object, 1); 
					string id = string.Empty;
					if (References.Contains(ControlStatement.CompleteStatement))
						id = ControlStatement.CompleteStatement.ID;
					else
					{
						References.Add(ControlStatement.CompleteStatement);
						System.Type CompleteStatementType = ControlStatement.CompleteStatement.GetType();
						Set(CompleteStatementObject, 1, CompleteStatementType.AssemblyQualifiedName, "CompleteStatement");
						GetSerializer(CompleteStatementType).SerializeInternal(AddObject(CompleteStatementObject, 2), ControlStatement.CompleteStatement, CompleteStatementType, References);
					}
					Set(CompleteStatementObject, 0, id, "CompleteStatement");
				}
				// ID
				Set(Object, 0, ControlStatement.ID, "ID");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.ControlStatement[] ControlStatementArray = (VisualScriptTool.Language.Statements.Control.ControlStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						ControlStatementArray[i] = null;
						continue;
					}
					ControlStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Control.ControlStatement>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)ControlStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.ControlStatement ControlStatement = (VisualScriptTool.Language.Statements.Control.ControlStatement)CreateInstance();
				// CompleteStatement
				ISerializeObject CompleteStatementObject = Get<ISerializeObject>(Object, 1, null);
				if (CompleteStatementObject != null)
				{
					ISerializeObject CompleteStatementObjectValue = Get<ISerializeObject>(Object, 1); 
					if (Contains(CompleteStatementObjectValue, 1))
					{
						Serializer CompleteStatementSerializer = GetSerializer(System.Type.GetType(Get<string>(CompleteStatementObjectValue, 1)));
						ControlStatement.CompleteStatement = CompleteStatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(CompleteStatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[ControlStatement.CompleteStatement.ID] = ControlStatement.CompleteStatement;
					}
					else
					{
						string id = Get<string>(CompleteStatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, ControlStatement, ControlStatement.GetType().GetProperty("CompleteStatement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					ControlStatement.CompleteStatement = null;
				// ID
				ControlStatement.ID = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)ControlStatement;
			}
			return returnValue;
		}

	}
}
#endif