// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class EntrypointStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.EntrypointStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.EntrypointStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.EntrypointStatement[] EntrypointStatementArray = null;
				if (InstanceType.IsArray())
					EntrypointStatementArray = (VisualScriptTool.Language.Statements.EntrypointStatement[])Instance;
				else
					EntrypointStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.EntrypointStatement>)Instance).ToArray();
				for (int i = 0; i < EntrypointStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.EntrypointStatement element = EntrypointStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.EntrypointStatement EntrypointStatement = (VisualScriptTool.Language.Statements.EntrypointStatement)Instance;
				// Statement
				if (EntrypointStatement.Statement == null)
					Set<object>(Object, 2, null, "Statement");
				else
				{
					ISerializeObject StatementObject = AddObject(Object, 2); 
					string id = string.Empty;
					if (References.Contains(EntrypointStatement.Statement))
						id = EntrypointStatement.Statement.ID;
					else
					{
						References.Add(EntrypointStatement.Statement);
						System.Type StatementType = EntrypointStatement.Statement.GetType();
						Set(StatementObject, 1, StatementType.AssemblyQualifiedName, "Statement");
						GetSerializer(StatementType).SerializeInternal(AddObject(StatementObject, 2), EntrypointStatement.Statement, StatementType, References);
					}
					Set(StatementObject, 0, id, "Statement");
				}
				// CompleteStatement
				if (EntrypointStatement.CompleteStatement == null)
					Set<object>(Object, 1, null, "CompleteStatement");
				else
				{
					ISerializeObject CompleteStatementObject = AddObject(Object, 1); 
					string id = string.Empty;
					if (References.Contains(EntrypointStatement.CompleteStatement))
						id = EntrypointStatement.CompleteStatement.ID;
					else
					{
						References.Add(EntrypointStatement.CompleteStatement);
						System.Type CompleteStatementType = EntrypointStatement.CompleteStatement.GetType();
						Set(CompleteStatementObject, 1, CompleteStatementType.AssemblyQualifiedName, "CompleteStatement");
						GetSerializer(CompleteStatementType).SerializeInternal(AddObject(CompleteStatementObject, 2), EntrypointStatement.CompleteStatement, CompleteStatementType, References);
					}
					Set(CompleteStatementObject, 0, id, "CompleteStatement");
				}
				// ID
				Set(Object, 0, EntrypointStatement.ID, "ID");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.EntrypointStatement[] EntrypointStatementArray = (VisualScriptTool.Language.Statements.EntrypointStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						EntrypointStatementArray[i] = null;
						continue;
					}
					EntrypointStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.EntrypointStatement>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)EntrypointStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.EntrypointStatement EntrypointStatement = (VisualScriptTool.Language.Statements.EntrypointStatement)CreateInstance();
				// Statement
				ISerializeObject StatementObject = Get<ISerializeObject>(Object, 2, null);
				if (StatementObject != null)
				{
					ISerializeObject StatementObjectValue = Get<ISerializeObject>(Object, 2); 
					if (Contains(StatementObjectValue, 1))
					{
						Serializer StatementSerializer = GetSerializer(System.Type.GetType(Get<string>(StatementObjectValue, 1)));
						EntrypointStatement.Statement = StatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(StatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[EntrypointStatement.Statement.ID] = EntrypointStatement.Statement;
					}
					else
					{
						string id = Get<string>(StatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, EntrypointStatement, EntrypointStatement.GetType().GetProperty("Statement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					EntrypointStatement.Statement = null;
				// CompleteStatement
				ISerializeObject CompleteStatementObject = Get<ISerializeObject>(Object, 1, null);
				if (CompleteStatementObject != null)
				{
					ISerializeObject CompleteStatementObjectValue = Get<ISerializeObject>(Object, 1); 
					if (Contains(CompleteStatementObjectValue, 1))
					{
						Serializer CompleteStatementSerializer = GetSerializer(System.Type.GetType(Get<string>(CompleteStatementObjectValue, 1)));
						EntrypointStatement.CompleteStatement = CompleteStatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(CompleteStatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[EntrypointStatement.CompleteStatement.ID] = EntrypointStatement.CompleteStatement;
					}
					else
					{
						string id = Get<string>(CompleteStatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, EntrypointStatement, EntrypointStatement.GetType().GetProperty("CompleteStatement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					EntrypointStatement.CompleteStatement = null;
				// ID
				EntrypointStatement.ID = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)EntrypointStatement;
			}
			return returnValue;
		}

	}
}
#endif