// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class ExecuterStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.ExecuterStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.ExecuterStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.ExecuterStatement[] ExecuterStatementArray = null;
				if (InstanceType.IsArray())
					ExecuterStatementArray = (VisualScriptTool.Language.Statements.ExecuterStatement[])Instance;
				else
					ExecuterStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.ExecuterStatement>)Instance).ToArray();
				for (int i = 0; i < ExecuterStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.ExecuterStatement element = ExecuterStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.ExecuterStatement ExecuterStatement = (VisualScriptTool.Language.Statements.ExecuterStatement)Instance;
				// Statement
				if (ExecuterStatement.Statement == null)
					Set<object>(Object, 1, null, "Statement");
				else
				{
					ISerializeObject StatementObject = AddObject(Object, 1); 
					string id = string.Empty;
					if (References.Contains(ExecuterStatement.Statement))
						id = ExecuterStatement.Statement.ID;
					else
					{
						References.Add(ExecuterStatement.Statement);
						System.Type StatementType = ExecuterStatement.Statement.GetType();
						Set(StatementObject, 1, StatementType.AssemblyQualifiedName, "Statement");
						GetSerializer(StatementType).SerializeInternal(AddObject(StatementObject, 2), ExecuterStatement.Statement, StatementType, References);
					}
					Set(StatementObject, 0, id, "Statement");
				}
				// ID
				Set(Object, 0, ExecuterStatement.ID, "ID");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.ExecuterStatement[] ExecuterStatementArray = (VisualScriptTool.Language.Statements.ExecuterStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						ExecuterStatementArray[i] = null;
						continue;
					}
					ExecuterStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.ExecuterStatement>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)ExecuterStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.ExecuterStatement ExecuterStatement = (VisualScriptTool.Language.Statements.ExecuterStatement)CreateInstance();
				// Statement
				ISerializeObject StatementObject = Get<ISerializeObject>(Object, 1, null);
				if (StatementObject != null)
				{
					ISerializeObject StatementObjectValue = Get<ISerializeObject>(Object, 1); 
					if (Contains(StatementObjectValue, 1))
					{
						Serializer StatementSerializer = GetSerializer(System.Type.GetType(Get<string>(StatementObjectValue, 1)));
						ExecuterStatement.Statement = StatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(StatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[ExecuterStatement.Statement.ID] = ExecuterStatement.Statement;
					}
					else
					{
						string id = Get<string>(StatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, ExecuterStatement, ExecuterStatement.GetType().GetProperty("Statement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					ExecuterStatement.Statement = null;
				// ID
				ExecuterStatement.ID = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)ExecuterStatement;
			}
			return returnValue;
		}

	}
}
#endif