// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class ForStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Control.ForStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Control.ForStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.ForStatement[] ForStatementArray = null;
				if (InstanceType.IsArray())
					ForStatementArray = (VisualScriptTool.Language.Statements.Control.ForStatement[])Instance;
				else
					ForStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Control.ForStatement>)Instance).ToArray();
				for (int i = 0; i < ForStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Control.ForStatement element = ForStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.ForStatement ForStatement = (VisualScriptTool.Language.Statements.Control.ForStatement)Instance;
				// First
				if (ForStatement.First == null)
					Set<object>(Object, 2, null, "First");
				else
				{
					ISerializeObject FirstObject = AddObject(Object, 2); 
					string id = string.Empty;
					if (References.Contains(ForStatement.First))
						id = ForStatement.First.ID;
					else
					{
						References.Add(ForStatement.First);
						System.Type FirstType = ForStatement.First.GetType();
						Set(FirstObject, 1, FirstType.AssemblyQualifiedName, "First");
						GetSerializer(FirstType).SerializeInternal(AddObject(FirstObject, 2), ForStatement.First, FirstType, References);
					}
					Set(FirstObject, 0, id, "First");
				}
				// FirstDefaultValue
				ISerializeObject FirstDefaultValueObject = AddObject(Object, 3); 
				System.Type FirstDefaultValueType = ForStatement.FirstDefaultValue.GetType();
				Set(FirstDefaultValueObject, 1, FirstDefaultValueType.AssemblyQualifiedName, "FirstDefaultValue");
				GetSerializer(FirstDefaultValueType).SerializeInternal(AddObject(FirstDefaultValueObject, 2), ForStatement.FirstDefaultValue, FirstDefaultValueType, References);
				// Last
				if (ForStatement.Last == null)
					Set<object>(Object, 4, null, "Last");
				else
				{
					ISerializeObject LastObject = AddObject(Object, 4); 
					string id = string.Empty;
					if (References.Contains(ForStatement.Last))
						id = ForStatement.Last.ID;
					else
					{
						References.Add(ForStatement.Last);
						System.Type LastType = ForStatement.Last.GetType();
						Set(LastObject, 1, LastType.AssemblyQualifiedName, "Last");
						GetSerializer(LastType).SerializeInternal(AddObject(LastObject, 2), ForStatement.Last, LastType, References);
					}
					Set(LastObject, 0, id, "Last");
				}
				// LastDefaultValue
				ISerializeObject LastDefaultValueObject = AddObject(Object, 5); 
				System.Type LastDefaultValueType = ForStatement.LastDefaultValue.GetType();
				Set(LastDefaultValueObject, 1, LastDefaultValueType.AssemblyQualifiedName, "LastDefaultValue");
				GetSerializer(LastDefaultValueType).SerializeInternal(AddObject(LastDefaultValueObject, 2), ForStatement.LastDefaultValue, LastDefaultValueType, References);
				// Step
				if (ForStatement.Step == null)
					Set<object>(Object, 6, null, "Step");
				else
				{
					ISerializeObject StepObject = AddObject(Object, 6); 
					string id = string.Empty;
					if (References.Contains(ForStatement.Step))
						id = ForStatement.Step.ID;
					else
					{
						References.Add(ForStatement.Step);
						System.Type StepType = ForStatement.Step.GetType();
						Set(StepObject, 1, StepType.AssemblyQualifiedName, "Step");
						GetSerializer(StepType).SerializeInternal(AddObject(StepObject, 2), ForStatement.Step, StepType, References);
					}
					Set(StepObject, 0, id, "Step");
				}
				// StepDefaultValue
				ISerializeObject StepDefaultValueObject = AddObject(Object, 7); 
				System.Type StepDefaultValueType = ForStatement.StepDefaultValue.GetType();
				Set(StepDefaultValueObject, 1, StepDefaultValueType.AssemblyQualifiedName, "StepDefaultValue");
				GetSerializer(StepDefaultValueType).SerializeInternal(AddObject(StepDefaultValueObject, 2), ForStatement.StepDefaultValue, StepDefaultValueType, References);
				// Statement
				if (ForStatement.Statement == null)
					Set<object>(Object, 8, null, "Statement");
				else
				{
					ISerializeObject StatementObject = AddObject(Object, 8); 
					string id = string.Empty;
					if (References.Contains(ForStatement.Statement))
						id = ForStatement.Statement.ID;
					else
					{
						References.Add(ForStatement.Statement);
						System.Type StatementType = ForStatement.Statement.GetType();
						Set(StatementObject, 1, StatementType.AssemblyQualifiedName, "Statement");
						GetSerializer(StatementType).SerializeInternal(AddObject(StatementObject, 2), ForStatement.Statement, StatementType, References);
					}
					Set(StatementObject, 0, id, "Statement");
				}
				// CompleteStatement
				if (ForStatement.CompleteStatement == null)
					Set<object>(Object, 1, null, "CompleteStatement");
				else
				{
					ISerializeObject CompleteStatementObject = AddObject(Object, 1); 
					string id = string.Empty;
					if (References.Contains(ForStatement.CompleteStatement))
						id = ForStatement.CompleteStatement.ID;
					else
					{
						References.Add(ForStatement.CompleteStatement);
						System.Type CompleteStatementType = ForStatement.CompleteStatement.GetType();
						Set(CompleteStatementObject, 1, CompleteStatementType.AssemblyQualifiedName, "CompleteStatement");
						GetSerializer(CompleteStatementType).SerializeInternal(AddObject(CompleteStatementObject, 2), ForStatement.CompleteStatement, CompleteStatementType, References);
					}
					Set(CompleteStatementObject, 0, id, "CompleteStatement");
				}
				// ID
				Set(Object, 0, ForStatement.ID, "ID");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.ForStatement[] ForStatementArray = (VisualScriptTool.Language.Statements.Control.ForStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						ForStatementArray[i] = null;
						continue;
					}
					ForStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Control.ForStatement>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)ForStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.ForStatement ForStatement = (VisualScriptTool.Language.Statements.Control.ForStatement)CreateInstance();
				// First
				ISerializeObject FirstObject = Get<ISerializeObject>(Object, 2, null);
				if (FirstObject != null)
				{
					ISerializeObject FirstObjectValue = Get<ISerializeObject>(Object, 2); 
					if (Contains(FirstObjectValue, 1))
					{
						Serializer FirstSerializer = GetSerializer(System.Type.GetType(Get<string>(FirstObjectValue, 1)));
						ForStatement.First = FirstSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.VariableStatement>(Get<ISerializeObject>(FirstObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[ForStatement.First.ID] = ForStatement.First;
					}
					else
					{
						string id = Get<string>(FirstObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, ForStatement, ForStatement.GetType().GetProperty("First", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					ForStatement.First = null;
				// FirstDefaultValue
				ISerializeObject FirstDefaultValueObject = Get<ISerializeObject>(Object, 3, null);
				if (FirstDefaultValueObject != null)
				{
					ISerializeObject FirstDefaultValueObjectValue = Get<ISerializeObject>(Object, 3); 
					Serializer FirstDefaultValueSerializer = GetSerializer(System.Type.GetType(Get<string>(FirstDefaultValueObjectValue, 1)));
					ForStatement.FirstDefaultValue = FirstDefaultValueSerializer.DeserializeInternal<VisualScriptTool.Language.AnyDataType>(Get<ISerializeObject>(FirstDefaultValueObjectValue, 2), StatementIDs, Resolvers);
				}
				// Last
				ISerializeObject LastObject = Get<ISerializeObject>(Object, 4, null);
				if (LastObject != null)
				{
					ISerializeObject LastObjectValue = Get<ISerializeObject>(Object, 4); 
					if (Contains(LastObjectValue, 1))
					{
						Serializer LastSerializer = GetSerializer(System.Type.GetType(Get<string>(LastObjectValue, 1)));
						ForStatement.Last = LastSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.VariableStatement>(Get<ISerializeObject>(LastObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[ForStatement.Last.ID] = ForStatement.Last;
					}
					else
					{
						string id = Get<string>(LastObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, ForStatement, ForStatement.GetType().GetProperty("Last", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					ForStatement.Last = null;
				// LastDefaultValue
				ISerializeObject LastDefaultValueObject = Get<ISerializeObject>(Object, 5, null);
				if (LastDefaultValueObject != null)
				{
					ISerializeObject LastDefaultValueObjectValue = Get<ISerializeObject>(Object, 5); 
					Serializer LastDefaultValueSerializer = GetSerializer(System.Type.GetType(Get<string>(LastDefaultValueObjectValue, 1)));
					ForStatement.LastDefaultValue = LastDefaultValueSerializer.DeserializeInternal<VisualScriptTool.Language.AnyDataType>(Get<ISerializeObject>(LastDefaultValueObjectValue, 2), StatementIDs, Resolvers);
				}
				// Step
				ISerializeObject StepObject = Get<ISerializeObject>(Object, 6, null);
				if (StepObject != null)
				{
					ISerializeObject StepObjectValue = Get<ISerializeObject>(Object, 6); 
					if (Contains(StepObjectValue, 1))
					{
						Serializer StepSerializer = GetSerializer(System.Type.GetType(Get<string>(StepObjectValue, 1)));
						ForStatement.Step = StepSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.VariableStatement>(Get<ISerializeObject>(StepObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[ForStatement.Step.ID] = ForStatement.Step;
					}
					else
					{
						string id = Get<string>(StepObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, ForStatement, ForStatement.GetType().GetProperty("Step", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					ForStatement.Step = null;
				// StepDefaultValue
				ISerializeObject StepDefaultValueObject = Get<ISerializeObject>(Object, 7, null);
				if (StepDefaultValueObject != null)
				{
					ISerializeObject StepDefaultValueObjectValue = Get<ISerializeObject>(Object, 7); 
					Serializer StepDefaultValueSerializer = GetSerializer(System.Type.GetType(Get<string>(StepDefaultValueObjectValue, 1)));
					ForStatement.StepDefaultValue = StepDefaultValueSerializer.DeserializeInternal<VisualScriptTool.Language.AnyDataType>(Get<ISerializeObject>(StepDefaultValueObjectValue, 2), StatementIDs, Resolvers);
				}
				// Statement
				ISerializeObject StatementObject = Get<ISerializeObject>(Object, 8, null);
				if (StatementObject != null)
				{
					ISerializeObject StatementObjectValue = Get<ISerializeObject>(Object, 8); 
					if (Contains(StatementObjectValue, 1))
					{
						Serializer StatementSerializer = GetSerializer(System.Type.GetType(Get<string>(StatementObjectValue, 1)));
						ForStatement.Statement = StatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(StatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[ForStatement.Statement.ID] = ForStatement.Statement;
					}
					else
					{
						string id = Get<string>(StatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, ForStatement, ForStatement.GetType().GetProperty("Statement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					ForStatement.Statement = null;
				// CompleteStatement
				ISerializeObject CompleteStatementObject = Get<ISerializeObject>(Object, 1, null);
				if (CompleteStatementObject != null)
				{
					ISerializeObject CompleteStatementObjectValue = Get<ISerializeObject>(Object, 1); 
					if (Contains(CompleteStatementObjectValue, 1))
					{
						Serializer CompleteStatementSerializer = GetSerializer(System.Type.GetType(Get<string>(CompleteStatementObjectValue, 1)));
						ForStatement.CompleteStatement = CompleteStatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(CompleteStatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[ForStatement.CompleteStatement.ID] = ForStatement.CompleteStatement;
					}
					else
					{
						string id = Get<string>(CompleteStatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, ForStatement, ForStatement.GetType().GetProperty("CompleteStatement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					ForStatement.CompleteStatement = null;
				// ID
				ForStatement.ID = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)ForStatement;
			}
			return returnValue;
		}

	}
}
#endif