// This File Has Generated By Compiler, Do Not Change It Manually
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class FunctionStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Control.FunctionStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Control.FunctionStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceTable references = new ReferenceTable();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			GUIDTable references = new GUIDTable();
			ResolverList resolverList = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, references, resolverList);
			for (int i = 0; i < resolverList.Count; ++i)
				resolverList[i].Reslve(references);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceTable References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.FunctionStatement[] FunctionStatementArray = null;
				if (InstanceType.IsArray())
					FunctionStatementArray = (VisualScriptTool.Language.Statements.Control.FunctionStatement[])Instance;
				else
					FunctionStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Control.FunctionStatement>)Instance).ToArray();
				for (int i = 0; i < FunctionStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Control.FunctionStatement element = FunctionStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.FunctionStatement FunctionStatement = (VisualScriptTool.Language.Statements.Control.FunctionStatement)Instance;
				// Name
				Set(Object, 0, FunctionStatement.Name);
				// MethodInfo
				Set(Object, 2, FunctionStatement.MethodInfo);
				// CompleteStatement
				if (FunctionStatement.CompleteStatement == null)
					Set(Object, 1, null);
				else
				{
					ISerializeObject CompleteStatementObject = AddObject(Object, 1); 
					string guid = string.Empty;
					if (References.ContainsKey(FunctionStatement.CompleteStatement))
						guid = References[FunctionStatement.CompleteStatement];
					else
					{
						guid = System.Guid.NewGuid().ToString();
						References[FunctionStatement.CompleteStatement] = guid;
						System.Type CompleteStatementType = FunctionStatement.CompleteStatement.GetType();
						Set(CompleteStatementObject, 1, CompleteStatementType.AssemblyQualifiedName);
						GetSerializer(CompleteStatementType).SerializeInternal(AddObject(CompleteStatementObject, 2), FunctionStatement.CompleteStatement, CompleteStatementType, References);
					}
					Set(CompleteStatementObject, 0, guid);
				}
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, GUIDTable References, ResolverList ResolverList)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.FunctionStatement[] FunctionStatementArray = (VisualScriptTool.Language.Statements.Control.FunctionStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						FunctionStatementArray[i] = null;
						continue;
					}
					FunctionStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Control.FunctionStatement>(Get<ISerializeObject>(arrayObj, 2), References, ResolverList); 
				}
				returnValue = (T)(object)FunctionStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.FunctionStatement FunctionStatement = (VisualScriptTool.Language.Statements.Control.FunctionStatement)CreateInstance();
				// Name
				FunctionStatement.Name = Get<System.String>(Object, 0, "");
				// MethodInfo
				FunctionStatement.MethodInfo = Get<System.String>(Object, 2, "");
				// CompleteStatement
				ISerializeObject CompleteStatementObject = Get<ISerializeObject>(Object, 1, null);
				if (CompleteStatementObject != null)
				{
					ISerializeObject CompleteStatementObjectValue = Get<ISerializeObject>(Object, 1); 
					string guid = Get<string>(CompleteStatementObjectValue, 0);
					if (Contains(CompleteStatementObjectValue, 1))
					{
						Serializer CompleteStatementSerializer = GetSerializer(System.Type.GetType(Get<string>(CompleteStatementObjectValue, 1)));
						FunctionStatement.CompleteStatement = CompleteStatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(CompleteStatementObjectValue, 2), References, ResolverList);
						References[guid] = FunctionStatement.CompleteStatement;
					}
					else
						ResolverList.Add(new ReferenceResolver(guid, FunctionStatement, FunctionStatement.GetType().GetProperty("CompleteStatement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
				}
				else
					FunctionStatement.CompleteStatement = null;
				returnValue = (T)(object)FunctionStatement;
			}
			return returnValue;
		}

	}
}