// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class FunctionCallStatementInstance_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Editor.Language.FunctionCallStatementInstance); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Editor.Language.FunctionCallStatementInstance();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Editor.Language.FunctionCallStatementInstance[] FunctionCallStatementInstanceArray = null;
				if (InstanceType.IsArray())
					FunctionCallStatementInstanceArray = (VisualScriptTool.Editor.Language.FunctionCallStatementInstance[])Instance;
				else
					FunctionCallStatementInstanceArray = ((System.Collections.Generic.List<VisualScriptTool.Editor.Language.FunctionCallStatementInstance>)Instance).ToArray();
				for (int i = 0; i < FunctionCallStatementInstanceArray.Length; ++i)
				{
					VisualScriptTool.Editor.Language.FunctionCallStatementInstance element = FunctionCallStatementInstanceArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Editor.Language.FunctionCallStatementInstance FunctionCallStatementInstance = (VisualScriptTool.Editor.Language.FunctionCallStatementInstance)Instance;
				// Statement
				if (FunctionCallStatementInstance.Statement == null)
					Set<object>(Object, 3, null, "Statement");
				else
				{
					ISerializeObject StatementObject = AddObject(Object, 3); 
					string id = string.Empty;
					if (References.Contains(FunctionCallStatementInstance.Statement))
						id = FunctionCallStatementInstance.Statement.ID;
					else
					{
						References.Add(FunctionCallStatementInstance.Statement);
						System.Type StatementType = FunctionCallStatementInstance.Statement.GetType();
						Set(StatementObject, 1, StatementType.AssemblyQualifiedName, "Statement");
						GetSerializer(StatementType).SerializeInternal(AddObject(StatementObject, 2), FunctionCallStatementInstance.Statement, StatementType, References);
					}
					Set(StatementObject, 0, id, "Statement");
				}
				// Position
				ISerializeObject PositionObject = AddObject(Object, 0); 
				System.Type PositionType = FunctionCallStatementInstance.Position.GetType();
				Set(PositionObject, 1, PositionType.AssemblyQualifiedName, "Position");
				GetSerializer(PositionType).SerializeInternal(AddObject(PositionObject, 2), FunctionCallStatementInstance.Position, PositionType, References);
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Editor.Language.FunctionCallStatementInstance[] FunctionCallStatementInstanceArray = (VisualScriptTool.Editor.Language.FunctionCallStatementInstance[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						FunctionCallStatementInstanceArray[i] = null;
						continue;
					}
					FunctionCallStatementInstanceArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Editor.Language.FunctionCallStatementInstance>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)FunctionCallStatementInstanceArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Editor.Language.FunctionCallStatementInstance FunctionCallStatementInstance = (VisualScriptTool.Editor.Language.FunctionCallStatementInstance)CreateInstance();
				// Statement
				ISerializeObject StatementObject = Get<ISerializeObject>(Object, 3, null);
				if (StatementObject != null)
				{
					ISerializeObject StatementObjectValue = Get<ISerializeObject>(Object, 3); 
					if (Contains(StatementObjectValue, 1))
					{
						Serializer StatementSerializer = GetSerializer(System.Type.GetType(Get<string>(StatementObjectValue, 1)));
						FunctionCallStatementInstance.Statement = StatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(StatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[FunctionCallStatementInstance.Statement.ID] = FunctionCallStatementInstance.Statement;
					}
					else
					{
						string id = Get<string>(StatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, FunctionCallStatementInstance, FunctionCallStatementInstance.GetType().GetProperty("Statement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					FunctionCallStatementInstance.Statement = null;
				// Position
				ISerializeObject PositionObject = Get<ISerializeObject>(Object, 0, null);
				if (PositionObject != null)
				{
					ISerializeObject PositionObjectValue = Get<ISerializeObject>(Object, 0); 
					Serializer PositionSerializer = GetSerializer(System.Type.GetType(Get<string>(PositionObjectValue, 1)));
					FunctionCallStatementInstance.Position = PositionSerializer.DeserializeInternal<System.Drawing.PointF>(Get<ISerializeObject>(PositionObjectValue, 2), StatementIDs, Resolvers);
				}
				returnValue = (T)(object)FunctionCallStatementInstance;
				FunctionCallStatementInstance.OnPostLoad();
			}
			return returnValue;
		}

	}
}
#endif