// This File Has Generated By Compiler, Do Not Change It Manually
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class IfStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Control.IfStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Control.IfStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceTable references = new ReferenceTable();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			GUIDTable references = new GUIDTable();
			ResolverList resolverList = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, references, resolverList);
			for (int i = 0; i < resolverList.Count; ++i)
				resolverList[i].Reslve(references);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceTable References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.IfStatement[] IfStatementArray = null;
				if (InstanceType.IsArray())
					IfStatementArray = (VisualScriptTool.Language.Statements.Control.IfStatement[])Instance;
				else
					IfStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Control.IfStatement>)Instance).ToArray();
				for (int i = 0; i < IfStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Control.IfStatement element = IfStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.IfStatement IfStatement = (VisualScriptTool.Language.Statements.Control.IfStatement)Instance;
				// Condition
				if (IfStatement.Condition == null)
					Set(Object, 2, null);
				else
				{
					ISerializeObject ConditionObject = AddObject(Object, 2); 
					string guid = string.Empty;
					if (References.ContainsKey(IfStatement.Condition))
						guid = References[IfStatement.Condition];
					else
					{
						guid = System.Guid.NewGuid().ToString();
						References[IfStatement.Condition] = guid;
						System.Type ConditionType = IfStatement.Condition.GetType();
						Set(ConditionObject, 1, ConditionType.AssemblyQualifiedName);
						GetSerializer(ConditionType).SerializeInternal(AddObject(ConditionObject, 2), IfStatement.Condition, ConditionType, References);
					}
					Set(ConditionObject, 0, guid);
				}
				// Statement
				if (IfStatement.Statement == null)
					Set(Object, 3, null);
				else
				{
					ISerializeObject StatementObject = AddObject(Object, 3); 
					string guid = string.Empty;
					if (References.ContainsKey(IfStatement.Statement))
						guid = References[IfStatement.Statement];
					else
					{
						guid = System.Guid.NewGuid().ToString();
						References[IfStatement.Statement] = guid;
						System.Type StatementType = IfStatement.Statement.GetType();
						Set(StatementObject, 1, StatementType.AssemblyQualifiedName);
						GetSerializer(StatementType).SerializeInternal(AddObject(StatementObject, 2), IfStatement.Statement, StatementType, References);
					}
					Set(StatementObject, 0, guid);
				}
				// ElseStatment
				if (IfStatement.ElseStatment == null)
					Set(Object, 4, null);
				else
				{
					ISerializeObject ElseStatmentObject = AddObject(Object, 4); 
					string guid = string.Empty;
					if (References.ContainsKey(IfStatement.ElseStatment))
						guid = References[IfStatement.ElseStatment];
					else
					{
						guid = System.Guid.NewGuid().ToString();
						References[IfStatement.ElseStatment] = guid;
						System.Type ElseStatmentType = IfStatement.ElseStatment.GetType();
						Set(ElseStatmentObject, 1, ElseStatmentType.AssemblyQualifiedName);
						GetSerializer(ElseStatmentType).SerializeInternal(AddObject(ElseStatmentObject, 2), IfStatement.ElseStatment, ElseStatmentType, References);
					}
					Set(ElseStatmentObject, 0, guid);
				}
				// CompleteStatement
				if (IfStatement.CompleteStatement == null)
					Set(Object, 1, null);
				else
				{
					ISerializeObject CompleteStatementObject = AddObject(Object, 1); 
					string guid = string.Empty;
					if (References.ContainsKey(IfStatement.CompleteStatement))
						guid = References[IfStatement.CompleteStatement];
					else
					{
						guid = System.Guid.NewGuid().ToString();
						References[IfStatement.CompleteStatement] = guid;
						System.Type CompleteStatementType = IfStatement.CompleteStatement.GetType();
						Set(CompleteStatementObject, 1, CompleteStatementType.AssemblyQualifiedName);
						GetSerializer(CompleteStatementType).SerializeInternal(AddObject(CompleteStatementObject, 2), IfStatement.CompleteStatement, CompleteStatementType, References);
					}
					Set(CompleteStatementObject, 0, guid);
				}
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, GUIDTable References, ResolverList ResolverList)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.IfStatement[] IfStatementArray = (VisualScriptTool.Language.Statements.Control.IfStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						IfStatementArray[i] = null;
						continue;
					}
					IfStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Control.IfStatement>(Get<ISerializeObject>(arrayObj, 2), References, ResolverList); 
				}
				returnValue = (T)(object)IfStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.IfStatement IfStatement = (VisualScriptTool.Language.Statements.Control.IfStatement)CreateInstance();
				// Condition
				ISerializeObject ConditionObject = Get<ISerializeObject>(Object, 2, null);
				if (ConditionObject != null)
				{
					ISerializeObject ConditionObjectValue = Get<ISerializeObject>(Object, 2); 
					string guid = Get<string>(ConditionObjectValue, 0);
					if (Contains(ConditionObjectValue, 1))
					{
						Serializer ConditionSerializer = GetSerializer(System.Type.GetType(Get<string>(ConditionObjectValue, 1)));
						IfStatement.Condition = ConditionSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.Variables.BooleanVariable>(Get<ISerializeObject>(ConditionObjectValue, 2), References, ResolverList);
						References[guid] = IfStatement.Condition;
					}
					else
						ResolverList.Add(new ReferenceResolver(guid, IfStatement, IfStatement.GetType().GetProperty("Condition", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
				}
				else
					IfStatement.Condition = null;
				// Statement
				ISerializeObject StatementObject = Get<ISerializeObject>(Object, 3, null);
				if (StatementObject != null)
				{
					ISerializeObject StatementObjectValue = Get<ISerializeObject>(Object, 3); 
					string guid = Get<string>(StatementObjectValue, 0);
					if (Contains(StatementObjectValue, 1))
					{
						Serializer StatementSerializer = GetSerializer(System.Type.GetType(Get<string>(StatementObjectValue, 1)));
						IfStatement.Statement = StatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(StatementObjectValue, 2), References, ResolverList);
						References[guid] = IfStatement.Statement;
					}
					else
						ResolverList.Add(new ReferenceResolver(guid, IfStatement, IfStatement.GetType().GetProperty("Statement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
				}
				else
					IfStatement.Statement = null;
				// ElseStatment
				ISerializeObject ElseStatmentObject = Get<ISerializeObject>(Object, 4, null);
				if (ElseStatmentObject != null)
				{
					ISerializeObject ElseStatmentObjectValue = Get<ISerializeObject>(Object, 4); 
					string guid = Get<string>(ElseStatmentObjectValue, 0);
					if (Contains(ElseStatmentObjectValue, 1))
					{
						Serializer ElseStatmentSerializer = GetSerializer(System.Type.GetType(Get<string>(ElseStatmentObjectValue, 1)));
						IfStatement.ElseStatment = ElseStatmentSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(ElseStatmentObjectValue, 2), References, ResolverList);
						References[guid] = IfStatement.ElseStatment;
					}
					else
						ResolverList.Add(new ReferenceResolver(guid, IfStatement, IfStatement.GetType().GetProperty("ElseStatment", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
				}
				else
					IfStatement.ElseStatment = null;
				// CompleteStatement
				ISerializeObject CompleteStatementObject = Get<ISerializeObject>(Object, 1, null);
				if (CompleteStatementObject != null)
				{
					ISerializeObject CompleteStatementObjectValue = Get<ISerializeObject>(Object, 1); 
					string guid = Get<string>(CompleteStatementObjectValue, 0);
					if (Contains(CompleteStatementObjectValue, 1))
					{
						Serializer CompleteStatementSerializer = GetSerializer(System.Type.GetType(Get<string>(CompleteStatementObjectValue, 1)));
						IfStatement.CompleteStatement = CompleteStatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(CompleteStatementObjectValue, 2), References, ResolverList);
						References[guid] = IfStatement.CompleteStatement;
					}
					else
						ResolverList.Add(new ReferenceResolver(guid, IfStatement, IfStatement.GetType().GetProperty("CompleteStatement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
				}
				else
					IfStatement.CompleteStatement = null;
				returnValue = (T)(object)IfStatement;
			}
			return returnValue;
		}

	}
}