// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class IfStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Control.IfStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Control.IfStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.IfStatement[] IfStatementArray = null;
				if (InstanceType.IsArray())
					IfStatementArray = (VisualScriptTool.Language.Statements.Control.IfStatement[])Instance;
				else
					IfStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Control.IfStatement>)Instance).ToArray();
				for (int i = 0; i < IfStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Control.IfStatement element = IfStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.IfStatement IfStatement = (VisualScriptTool.Language.Statements.Control.IfStatement)Instance;
				// Condition
				if (IfStatement.Condition == null)
					Set<object>(Object, 2, null, "Condition");
				else
				{
					ISerializeObject ConditionObject = AddObject(Object, 2); 
					string id = string.Empty;
					if (References.Contains(IfStatement.Condition))
						id = IfStatement.Condition.ID;
					else
					{
						References.Add(IfStatement.Condition);
						System.Type ConditionType = IfStatement.Condition.GetType();
						Set(ConditionObject, 1, ConditionType.AssemblyQualifiedName, "Condition");
						GetSerializer(ConditionType).SerializeInternal(AddObject(ConditionObject, 2), IfStatement.Condition, ConditionType, References);
					}
					Set(ConditionObject, 0, id, "Condition");
				}
				// ConditionDefaultValue
				Set(Object, 5, IfStatement.ConditionDefaultValue, "ConditionDefaultValue");
				// Statement
				if (IfStatement.Statement == null)
					Set<object>(Object, 3, null, "Statement");
				else
				{
					ISerializeObject StatementObject = AddObject(Object, 3); 
					string id = string.Empty;
					if (References.Contains(IfStatement.Statement))
						id = IfStatement.Statement.ID;
					else
					{
						References.Add(IfStatement.Statement);
						System.Type StatementType = IfStatement.Statement.GetType();
						Set(StatementObject, 1, StatementType.AssemblyQualifiedName, "Statement");
						GetSerializer(StatementType).SerializeInternal(AddObject(StatementObject, 2), IfStatement.Statement, StatementType, References);
					}
					Set(StatementObject, 0, id, "Statement");
				}
				// ElseStatment
				if (IfStatement.ElseStatment == null)
					Set<object>(Object, 4, null, "ElseStatment");
				else
				{
					ISerializeObject ElseStatmentObject = AddObject(Object, 4); 
					string id = string.Empty;
					if (References.Contains(IfStatement.ElseStatment))
						id = IfStatement.ElseStatment.ID;
					else
					{
						References.Add(IfStatement.ElseStatment);
						System.Type ElseStatmentType = IfStatement.ElseStatment.GetType();
						Set(ElseStatmentObject, 1, ElseStatmentType.AssemblyQualifiedName, "ElseStatment");
						GetSerializer(ElseStatmentType).SerializeInternal(AddObject(ElseStatmentObject, 2), IfStatement.ElseStatment, ElseStatmentType, References);
					}
					Set(ElseStatmentObject, 0, id, "ElseStatment");
				}
				// CompleteStatement
				if (IfStatement.CompleteStatement == null)
					Set<object>(Object, 1, null, "CompleteStatement");
				else
				{
					ISerializeObject CompleteStatementObject = AddObject(Object, 1); 
					string id = string.Empty;
					if (References.Contains(IfStatement.CompleteStatement))
						id = IfStatement.CompleteStatement.ID;
					else
					{
						References.Add(IfStatement.CompleteStatement);
						System.Type CompleteStatementType = IfStatement.CompleteStatement.GetType();
						Set(CompleteStatementObject, 1, CompleteStatementType.AssemblyQualifiedName, "CompleteStatement");
						GetSerializer(CompleteStatementType).SerializeInternal(AddObject(CompleteStatementObject, 2), IfStatement.CompleteStatement, CompleteStatementType, References);
					}
					Set(CompleteStatementObject, 0, id, "CompleteStatement");
				}
				// ID
				Set(Object, 0, IfStatement.ID, "ID");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.IfStatement[] IfStatementArray = (VisualScriptTool.Language.Statements.Control.IfStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						IfStatementArray[i] = null;
						continue;
					}
					IfStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Control.IfStatement>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)IfStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.IfStatement IfStatement = (VisualScriptTool.Language.Statements.Control.IfStatement)CreateInstance();
				// Condition
				ISerializeObject ConditionObject = Get<ISerializeObject>(Object, 2, null);
				if (ConditionObject != null)
				{
					ISerializeObject ConditionObjectValue = Get<ISerializeObject>(Object, 2); 
					if (Contains(ConditionObjectValue, 1))
					{
						Serializer ConditionSerializer = GetSerializer(System.Type.GetType(Get<string>(ConditionObjectValue, 1)));
						IfStatement.Condition = ConditionSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.BooleanVariable>(Get<ISerializeObject>(ConditionObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[IfStatement.Condition.ID] = IfStatement.Condition;
					}
					else
					{
						string id = Get<string>(ConditionObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, IfStatement, IfStatement.GetType().GetProperty("Condition", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					IfStatement.Condition = null;
				// ConditionDefaultValue
				IfStatement.ConditionDefaultValue = Get<System.Boolean>(Object, 5, false);
				// Statement
				ISerializeObject StatementObject = Get<ISerializeObject>(Object, 3, null);
				if (StatementObject != null)
				{
					ISerializeObject StatementObjectValue = Get<ISerializeObject>(Object, 3); 
					if (Contains(StatementObjectValue, 1))
					{
						Serializer StatementSerializer = GetSerializer(System.Type.GetType(Get<string>(StatementObjectValue, 1)));
						IfStatement.Statement = StatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(StatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[IfStatement.Statement.ID] = IfStatement.Statement;
					}
					else
					{
						string id = Get<string>(StatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, IfStatement, IfStatement.GetType().GetProperty("Statement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					IfStatement.Statement = null;
				// ElseStatment
				ISerializeObject ElseStatmentObject = Get<ISerializeObject>(Object, 4, null);
				if (ElseStatmentObject != null)
				{
					ISerializeObject ElseStatmentObjectValue = Get<ISerializeObject>(Object, 4); 
					if (Contains(ElseStatmentObjectValue, 1))
					{
						Serializer ElseStatmentSerializer = GetSerializer(System.Type.GetType(Get<string>(ElseStatmentObjectValue, 1)));
						IfStatement.ElseStatment = ElseStatmentSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(ElseStatmentObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[IfStatement.ElseStatment.ID] = IfStatement.ElseStatment;
					}
					else
					{
						string id = Get<string>(ElseStatmentObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, IfStatement, IfStatement.GetType().GetProperty("ElseStatment", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					IfStatement.ElseStatment = null;
				// CompleteStatement
				ISerializeObject CompleteStatementObject = Get<ISerializeObject>(Object, 1, null);
				if (CompleteStatementObject != null)
				{
					ISerializeObject CompleteStatementObjectValue = Get<ISerializeObject>(Object, 1); 
					if (Contains(CompleteStatementObjectValue, 1))
					{
						Serializer CompleteStatementSerializer = GetSerializer(System.Type.GetType(Get<string>(CompleteStatementObjectValue, 1)));
						IfStatement.CompleteStatement = CompleteStatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(CompleteStatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[IfStatement.CompleteStatement.ID] = IfStatement.CompleteStatement;
					}
					else
					{
						string id = Get<string>(CompleteStatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, IfStatement, IfStatement.GetType().GetProperty("CompleteStatement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					IfStatement.CompleteStatement = null;
				// ID
				IfStatement.ID = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)IfStatement;
			}
			return returnValue;
		}

	}
}
#endif