// This File Has Generated By Compiler, Do Not Change It Manually
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class IntegerVariable_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceTable references = new ReferenceTable();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			GUIDTable references = new GUIDTable();
			ResolverList resolverList = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, references, resolverList);
			for (int i = 0; i < resolverList.Count; ++i)
				resolverList[i].Reslve(references);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceTable References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable[] IntegerVariableArray = null;
				if (InstanceType.IsArray())
					IntegerVariableArray = (VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable[])Instance;
				else
					IntegerVariableArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable>)Instance).ToArray();
				for (int i = 0; i < IntegerVariableArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable element = IntegerVariableArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable IntegerVariable = (VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable)Instance;
				// Value
				Set(Object, 2, IntegerVariable.Value);
				// Name
				Set(Object, 0, IntegerVariable.Name);
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, GUIDTable References, ResolverList ResolverList)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable[] IntegerVariableArray = (VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						IntegerVariableArray[i] = null;
						continue;
					}
					IntegerVariableArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable>(Get<ISerializeObject>(arrayObj, 2), References, ResolverList); 
				}
				returnValue = (T)(object)IntegerVariableArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable IntegerVariable = (VisualScriptTool.Language.Statements.Declaration.Variables.IntegerVariable)CreateInstance();
				// Value
				IntegerVariable.Value = Get<System.Int32>(Object, 2, 0);
				// Name
				IntegerVariable.Name = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)IntegerVariable;
			}
			return returnValue;
		}

	}
}