// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class StringVariable_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Declaration.StringVariable); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Declaration.StringVariable();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Declaration.StringVariable[] StringVariableArray = null;
				if (InstanceType.IsArray())
					StringVariableArray = (VisualScriptTool.Language.Statements.Declaration.StringVariable[])Instance;
				else
					StringVariableArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Declaration.StringVariable>)Instance).ToArray();
				for (int i = 0; i < StringVariableArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Declaration.StringVariable element = StringVariableArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Declaration.StringVariable StringVariable = (VisualScriptTool.Language.Statements.Declaration.StringVariable)Instance;
				// Value
				Set(Object, 2, StringVariable.Value, "Value");
				// Name
				Set(Object, 1, StringVariable.Name, "Name");
				// ID
				Set(Object, 0, StringVariable.ID, "ID");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Declaration.StringVariable[] StringVariableArray = (VisualScriptTool.Language.Statements.Declaration.StringVariable[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						StringVariableArray[i] = null;
						continue;
					}
					StringVariableArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.StringVariable>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)StringVariableArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Declaration.StringVariable StringVariable = (VisualScriptTool.Language.Statements.Declaration.StringVariable)CreateInstance();
				// Value
				StringVariable.Value = Get<System.String>(Object, 2, "");
				// Name
				StringVariable.Name = Get<System.String>(Object, 1, "");
				// ID
				StringVariable.ID = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)StringVariable;
			}
			return returnValue;
		}

	}
}
#endif