// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class VariableStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Declaration.VariableStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Declaration.VariableStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Declaration.VariableStatement[] VariableStatementArray = null;
				if (InstanceType.IsArray())
					VariableStatementArray = (VisualScriptTool.Language.Statements.Declaration.VariableStatement[])Instance;
				else
					VariableStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Declaration.VariableStatement>)Instance).ToArray();
				for (int i = 0; i < VariableStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Declaration.VariableStatement element = VariableStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Declaration.VariableStatement VariableStatement = (VisualScriptTool.Language.Statements.Declaration.VariableStatement)Instance;
				// Name
				Set(Object, 1, VariableStatement.Name, "Name");
				// Value
				ISerializeObject ValueObject = AddObject(Object, 3); 
				System.Type ValueType = VariableStatement.Value.GetType();
				Set(ValueObject, 1, ValueType.AssemblyQualifiedName, "Value");
				GetSerializer(ValueType).SerializeInternal(AddObject(ValueObject, 2), VariableStatement.Value, ValueType, References);
				// ID
				Set(Object, 0, VariableStatement.ID, "ID");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Declaration.VariableStatement[] VariableStatementArray = (VisualScriptTool.Language.Statements.Declaration.VariableStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						VariableStatementArray[i] = null;
						continue;
					}
					VariableStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.VariableStatement>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)VariableStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Declaration.VariableStatement VariableStatement = (VisualScriptTool.Language.Statements.Declaration.VariableStatement)CreateInstance();
				// Name
				VariableStatement.Name = Get<System.String>(Object, 1, "");
				// Value
				ISerializeObject ValueObject = Get<ISerializeObject>(Object, 3, null);
				if (ValueObject != null)
				{
					ISerializeObject ValueObjectValue = Get<ISerializeObject>(Object, 3); 
					Serializer ValueSerializer = GetSerializer(System.Type.GetType(Get<string>(ValueObjectValue, 1)));
					VariableStatement.Value = ValueSerializer.DeserializeInternal<VisualScriptTool.Language.AnyDataType>(Get<ISerializeObject>(ValueObjectValue, 2), StatementIDs, Resolvers);
				}
				// ID
				VariableStatement.ID = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)VariableStatement;
			}
			return returnValue;
		}

	}
}
#endif