// This File Has Generated By Compiler, Do Not Change It Manually
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class VariableSetterStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceTable references = new ReferenceTable();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			GUIDTable references = new GUIDTable();
			ResolverList resolverList = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, references, resolverList);
			for (int i = 0; i < resolverList.Count; ++i)
				resolverList[i].Reslve(references);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceTable References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement[] VariableSetterStatementArray = null;
				if (InstanceType.IsArray())
					VariableSetterStatementArray = (VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement[])Instance;
				else
					VariableSetterStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement>)Instance).ToArray();
				for (int i = 0; i < VariableSetterStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement element = VariableSetterStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement VariableSetterStatement = (VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement)Instance;
				// Variable
				if (VariableSetterStatement.Variable == null)
					Set(Object, 1, null);
				else
				{
					ISerializeObject VariableObject = AddObject(Object, 1); 
					string guid = string.Empty;
					if (References.ContainsKey(VariableSetterStatement.Variable))
						guid = References[VariableSetterStatement.Variable];
					else
					{
						guid = System.Guid.NewGuid().ToString();
						References[VariableSetterStatement.Variable] = guid;
						System.Type VariableType = VariableSetterStatement.Variable.GetType();
						Set(VariableObject, 1, VariableType.AssemblyQualifiedName);
						GetSerializer(VariableType).SerializeInternal(AddObject(VariableObject, 2), VariableSetterStatement.Variable, VariableType, References);
					}
					Set(VariableObject, 0, guid);
				}
				// Statement
				if (VariableSetterStatement.Statement == null)
					Set(Object, 2, null);
				else
				{
					ISerializeObject StatementObject = AddObject(Object, 2); 
					string guid = string.Empty;
					if (References.ContainsKey(VariableSetterStatement.Statement))
						guid = References[VariableSetterStatement.Statement];
					else
					{
						guid = System.Guid.NewGuid().ToString();
						References[VariableSetterStatement.Statement] = guid;
						System.Type StatementType = VariableSetterStatement.Statement.GetType();
						Set(StatementObject, 1, StatementType.AssemblyQualifiedName);
						GetSerializer(StatementType).SerializeInternal(AddObject(StatementObject, 2), VariableSetterStatement.Statement, StatementType, References);
					}
					Set(StatementObject, 0, guid);
				}
				// DefaultValue
				if (VariableSetterStatement.DefaultValue == null)
					Set(Object, 3, null);
				else
				{
					ISerializeObject DefaultValueObject = AddObject(Object, 3); 
					string guid = string.Empty;
					if (References.ContainsKey(VariableSetterStatement.DefaultValue))
						guid = References[VariableSetterStatement.DefaultValue];
					else
					{
						guid = System.Guid.NewGuid().ToString();
						References[VariableSetterStatement.DefaultValue] = guid;
						System.Type DefaultValueType = VariableSetterStatement.DefaultValue.GetType();
						Set(DefaultValueObject, 1, DefaultValueType.AssemblyQualifiedName);
						GetSerializer(DefaultValueType).SerializeInternal(AddObject(DefaultValueObject, 2), VariableSetterStatement.DefaultValue, DefaultValueType, References);
					}
					Set(DefaultValueObject, 0, guid);
				}
				// Name
				Set(Object, 0, VariableSetterStatement.Name);
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, GUIDTable References, ResolverList ResolverList)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement[] VariableSetterStatementArray = (VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						VariableSetterStatementArray[i] = null;
						continue;
					}
					VariableSetterStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement>(Get<ISerializeObject>(arrayObj, 2), References, ResolverList); 
				}
				returnValue = (T)(object)VariableSetterStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement VariableSetterStatement = (VisualScriptTool.Language.Statements.Declaration.Variables.VariableSetterStatement)CreateInstance();
				// Variable
				ISerializeObject VariableObject = Get<ISerializeObject>(Object, 1, null);
				if (VariableObject != null)
				{
					ISerializeObject VariableObjectValue = Get<ISerializeObject>(Object, 1); 
					string guid = Get<string>(VariableObjectValue, 0);
					if (Contains(VariableObjectValue, 1))
					{
						Serializer VariableSerializer = GetSerializer(System.Type.GetType(Get<string>(VariableObjectValue, 1)));
						VariableSetterStatement.Variable = VariableSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.Variables.VariableStatement>(Get<ISerializeObject>(VariableObjectValue, 2), References, ResolverList);
						References[guid] = VariableSetterStatement.Variable;
					}
					else
						ResolverList.Add(new ReferenceResolver(guid, VariableSetterStatement, VariableSetterStatement.GetType().GetProperty("Variable", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
				}
				else
					VariableSetterStatement.Variable = null;
				// Statement
				ISerializeObject StatementObject = Get<ISerializeObject>(Object, 2, null);
				if (StatementObject != null)
				{
					ISerializeObject StatementObjectValue = Get<ISerializeObject>(Object, 2); 
					string guid = Get<string>(StatementObjectValue, 0);
					if (Contains(StatementObjectValue, 1))
					{
						Serializer StatementSerializer = GetSerializer(System.Type.GetType(Get<string>(StatementObjectValue, 1)));
						VariableSetterStatement.Statement = StatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.Variables.VariableStatement>(Get<ISerializeObject>(StatementObjectValue, 2), References, ResolverList);
						References[guid] = VariableSetterStatement.Statement;
					}
					else
						ResolverList.Add(new ReferenceResolver(guid, VariableSetterStatement, VariableSetterStatement.GetType().GetProperty("Statement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
				}
				else
					VariableSetterStatement.Statement = null;
				// DefaultValue
				ISerializeObject DefaultValueObject = Get<ISerializeObject>(Object, 3, null);
				if (DefaultValueObject != null)
				{
					ISerializeObject DefaultValueObjectValue = Get<ISerializeObject>(Object, 3); 
					string guid = Get<string>(DefaultValueObjectValue, 0);
					if (Contains(DefaultValueObjectValue, 1))
					{
						Serializer DefaultValueSerializer = GetSerializer(System.Type.GetType(Get<string>(DefaultValueObjectValue, 1)));
						VariableSetterStatement.DefaultValue = DefaultValueSerializer.DeserializeInternal<System.Object>(Get<ISerializeObject>(DefaultValueObjectValue, 2), References, ResolverList);
						References[guid] = VariableSetterStatement.DefaultValue;
					}
					else
						ResolverList.Add(new ReferenceResolver(guid, VariableSetterStatement, VariableSetterStatement.GetType().GetProperty("DefaultValue", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
				}
				else
					VariableSetterStatement.DefaultValue = null;
				// Name
				VariableSetterStatement.Name = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)VariableSetterStatement;
			}
			return returnValue;
		}

	}
}