// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class VariableSetterStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Control.VariableSetterStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Control.VariableSetterStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.VariableSetterStatement[] VariableSetterStatementArray = null;
				if (InstanceType.IsArray())
					VariableSetterStatementArray = (VisualScriptTool.Language.Statements.Control.VariableSetterStatement[])Instance;
				else
					VariableSetterStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Control.VariableSetterStatement>)Instance).ToArray();
				for (int i = 0; i < VariableSetterStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Control.VariableSetterStatement element = VariableSetterStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.VariableSetterStatement VariableSetterStatement = (VisualScriptTool.Language.Statements.Control.VariableSetterStatement)Instance;
				// Name
				Set(Object, 2, VariableSetterStatement.Name, "Name");
				// Variable
				if (VariableSetterStatement.Variable == null)
					Set<object>(Object, 3, null, "Variable");
				else
				{
					ISerializeObject VariableObject = AddObject(Object, 3); 
					string id = string.Empty;
					if (References.Contains(VariableSetterStatement.Variable))
						id = VariableSetterStatement.Variable.ID;
					else
					{
						References.Add(VariableSetterStatement.Variable);
						System.Type VariableType = VariableSetterStatement.Variable.GetType();
						Set(VariableObject, 1, VariableType.AssemblyQualifiedName, "Variable");
						GetSerializer(VariableType).SerializeInternal(AddObject(VariableObject, 2), VariableSetterStatement.Variable, VariableType, References);
					}
					Set(VariableObject, 0, id, "Variable");
				}
				// Statement
				if (VariableSetterStatement.Statement == null)
					Set<object>(Object, 4, null, "Statement");
				else
				{
					ISerializeObject StatementObject = AddObject(Object, 4); 
					string id = string.Empty;
					if (References.Contains(VariableSetterStatement.Statement))
						id = VariableSetterStatement.Statement.ID;
					else
					{
						References.Add(VariableSetterStatement.Statement);
						System.Type StatementType = VariableSetterStatement.Statement.GetType();
						Set(StatementObject, 1, StatementType.AssemblyQualifiedName, "Statement");
						GetSerializer(StatementType).SerializeInternal(AddObject(StatementObject, 2), VariableSetterStatement.Statement, StatementType, References);
					}
					Set(StatementObject, 0, id, "Statement");
				}
				// DefaultValue
				if (VariableSetterStatement.DefaultValue == null)
					Set<object>(Object, 5, null, "DefaultValue");
				else
				{
					ISerializeObject DefaultValueObject = AddObject(Object, 5); 
					string id = string.Empty;
					if (References.Contains(VariableSetterStatement.DefaultValue))
						id = VariableSetterStatement.DefaultValue.ID;
					else
					{
						References.Add(VariableSetterStatement.DefaultValue);
						System.Type DefaultValueType = VariableSetterStatement.DefaultValue.GetType();
						Set(DefaultValueObject, 1, DefaultValueType.AssemblyQualifiedName, "DefaultValue");
						GetSerializer(DefaultValueType).SerializeInternal(AddObject(DefaultValueObject, 2), VariableSetterStatement.DefaultValue, DefaultValueType, References);
					}
					Set(DefaultValueObject, 0, id, "DefaultValue");
				}
				// CompleteStatement
				if (VariableSetterStatement.CompleteStatement == null)
					Set<object>(Object, 1, null, "CompleteStatement");
				else
				{
					ISerializeObject CompleteStatementObject = AddObject(Object, 1); 
					string id = string.Empty;
					if (References.Contains(VariableSetterStatement.CompleteStatement))
						id = VariableSetterStatement.CompleteStatement.ID;
					else
					{
						References.Add(VariableSetterStatement.CompleteStatement);
						System.Type CompleteStatementType = VariableSetterStatement.CompleteStatement.GetType();
						Set(CompleteStatementObject, 1, CompleteStatementType.AssemblyQualifiedName, "CompleteStatement");
						GetSerializer(CompleteStatementType).SerializeInternal(AddObject(CompleteStatementObject, 2), VariableSetterStatement.CompleteStatement, CompleteStatementType, References);
					}
					Set(CompleteStatementObject, 0, id, "CompleteStatement");
				}
				// ID
				Set(Object, 0, VariableSetterStatement.ID, "ID");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.VariableSetterStatement[] VariableSetterStatementArray = (VisualScriptTool.Language.Statements.Control.VariableSetterStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						VariableSetterStatementArray[i] = null;
						continue;
					}
					VariableSetterStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Control.VariableSetterStatement>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)VariableSetterStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.VariableSetterStatement VariableSetterStatement = (VisualScriptTool.Language.Statements.Control.VariableSetterStatement)CreateInstance();
				// Name
				VariableSetterStatement.Name = Get<System.String>(Object, 2, "");
				// Variable
				ISerializeObject VariableObject = Get<ISerializeObject>(Object, 3, null);
				if (VariableObject != null)
				{
					ISerializeObject VariableObjectValue = Get<ISerializeObject>(Object, 3); 
					if (Contains(VariableObjectValue, 1))
					{
						Serializer VariableSerializer = GetSerializer(System.Type.GetType(Get<string>(VariableObjectValue, 1)));
						VariableSetterStatement.Variable = VariableSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.VariableStatement>(Get<ISerializeObject>(VariableObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[VariableSetterStatement.Variable.ID] = VariableSetterStatement.Variable;
					}
					else
					{
						string id = Get<string>(VariableObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, VariableSetterStatement, VariableSetterStatement.GetType().GetProperty("Variable", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					VariableSetterStatement.Variable = null;
				// Statement
				ISerializeObject StatementObject = Get<ISerializeObject>(Object, 4, null);
				if (StatementObject != null)
				{
					ISerializeObject StatementObjectValue = Get<ISerializeObject>(Object, 4); 
					if (Contains(StatementObjectValue, 1))
					{
						Serializer StatementSerializer = GetSerializer(System.Type.GetType(Get<string>(StatementObjectValue, 1)));
						VariableSetterStatement.Statement = StatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.VariableStatement>(Get<ISerializeObject>(StatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[VariableSetterStatement.Statement.ID] = VariableSetterStatement.Statement;
					}
					else
					{
						string id = Get<string>(StatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, VariableSetterStatement, VariableSetterStatement.GetType().GetProperty("Statement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					VariableSetterStatement.Statement = null;
				// DefaultValue
				ISerializeObject DefaultValueObject = Get<ISerializeObject>(Object, 5, null);
				if (DefaultValueObject != null)
				{
					ISerializeObject DefaultValueObjectValue = Get<ISerializeObject>(Object, 5); 
					if (Contains(DefaultValueObjectValue, 1))
					{
						Serializer DefaultValueSerializer = GetSerializer(System.Type.GetType(Get<string>(DefaultValueObjectValue, 1)));
						VariableSetterStatement.DefaultValue = DefaultValueSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.UserDefinedStatement>(Get<ISerializeObject>(DefaultValueObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[VariableSetterStatement.DefaultValue.ID] = VariableSetterStatement.DefaultValue;
					}
					else
					{
						string id = Get<string>(DefaultValueObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, VariableSetterStatement, VariableSetterStatement.GetType().GetProperty("DefaultValue", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					VariableSetterStatement.DefaultValue = null;
				// CompleteStatement
				ISerializeObject CompleteStatementObject = Get<ISerializeObject>(Object, 1, null);
				if (CompleteStatementObject != null)
				{
					ISerializeObject CompleteStatementObjectValue = Get<ISerializeObject>(Object, 1); 
					if (Contains(CompleteStatementObjectValue, 1))
					{
						Serializer CompleteStatementSerializer = GetSerializer(System.Type.GetType(Get<string>(CompleteStatementObjectValue, 1)));
						VariableSetterStatement.CompleteStatement = CompleteStatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(CompleteStatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[VariableSetterStatement.CompleteStatement.ID] = VariableSetterStatement.CompleteStatement;
					}
					else
					{
						string id = Get<string>(CompleteStatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, VariableSetterStatement, VariableSetterStatement.GetType().GetProperty("CompleteStatement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					VariableSetterStatement.CompleteStatement = null;
				// ID
				VariableSetterStatement.ID = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)VariableSetterStatement;
			}
			return returnValue;
		}

	}
}
#endif