// This File Has Generated By Compiler, Do Not Change It Manually
#if !DISABLE_SERIALIZERS
using VisualScriptTool.Serialization;
using VisualScriptTool.Reflection;
namespace VisualScriptTool.Editor.Serializers
{
	class WhileStatement_Serializer : Serializer
	{
		public override System.Type Type
		{
			get { return typeof(VisualScriptTool.Language.Statements.Control.WhileStatement); }
		}

		public override object CreateInstance()
		{
			return new VisualScriptTool.Language.Statements.Control.WhileStatement();
		}

		public override void Serialize(ISerializeData Data, object Instance)
		{
			if (Data == null || Instance == null)
				throw new System.ArgumentNullException("Data and/or Instance cannot be null");
			System.Type instanceType = Instance.GetType();
			if (instanceType.IsArray())
				instanceType = instanceType.GetArrayElementType();
			else if (instanceType.IsList())
				instanceType = instanceType.GetListElementType();
			if (Type != instanceType)
				throw new System.InvalidCastException("Expected [" + Type.FullName + "]");
			instanceType = Instance.GetType();
			if ((Data is ISerializeObject && instanceType.IsArrayOrList()) || (Data is ISerializeArray && !instanceType.IsArrayOrList()))
				throw new System.ArgumentException("Data and Instance mismatch [" + Type.FullName + "]");
			ReferenceList references = new ReferenceList();
			SerializeInternal(Data, Instance, instanceType, references);
		}

		public override T Deserialize<T>(ISerializeData Data)
		{
			if (Data == null)
				throw new System.ArgumentNullException("Data cannot be null");
			StatementIDTable statementIDs = new StatementIDTable();
			ResolverList resolvers = new ResolverList();
			T returnValue = DeserializeInternal<T>(Data, statementIDs, resolvers);
			for (int i = 0; i < resolvers.Count; ++i)
				resolvers[i].Reslve(statementIDs);
			return returnValue;
		}

		public override void SerializeInternal(ISerializeData Data, object Instance, System.Type InstanceType, ReferenceList References)
		{
			if (InstanceType.IsArrayOrList())
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.WhileStatement[] WhileStatementArray = null;
				if (InstanceType.IsArray())
					WhileStatementArray = (VisualScriptTool.Language.Statements.Control.WhileStatement[])Instance;
				else
					WhileStatementArray = ((System.Collections.Generic.List<VisualScriptTool.Language.Statements.Control.WhileStatement>)Instance).ToArray();
				for (int i = 0; i < WhileStatementArray.Length; ++i)
				{
					VisualScriptTool.Language.Statements.Control.WhileStatement element = WhileStatementArray[i];
					if (element == null)
						Add(Array, null);
					else
					{
						ISerializeObject elementObject = AddObject(Array); 
						System.Type elementType = element.GetType();
						Set(elementObject, 1, elementType.AssemblyQualifiedName);
						GetSerializer(elementType).SerializeInternal(AddObject(elementObject, 2), element, elementType, References); 
					}
				}
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.WhileStatement WhileStatement = (VisualScriptTool.Language.Statements.Control.WhileStatement)Instance;
				// Condition
				if (WhileStatement.Condition == null)
					Set<object>(Object, 2, null, "Condition");
				else
				{
					ISerializeObject ConditionObject = AddObject(Object, 2); 
					string id = string.Empty;
					if (References.Contains(WhileStatement.Condition))
						id = WhileStatement.Condition.ID;
					else
					{
						References.Add(WhileStatement.Condition);
						System.Type ConditionType = WhileStatement.Condition.GetType();
						Set(ConditionObject, 1, ConditionType.AssemblyQualifiedName, "Condition");
						GetSerializer(ConditionType).SerializeInternal(AddObject(ConditionObject, 2), WhileStatement.Condition, ConditionType, References);
					}
					Set(ConditionObject, 0, id, "Condition");
				}
				// ConditionDefaultValue
				ISerializeObject ConditionDefaultValueObject = AddObject(Object, 4); 
				System.Type ConditionDefaultValueType = WhileStatement.ConditionDefaultValue.GetType();
				Set(ConditionDefaultValueObject, 1, ConditionDefaultValueType.AssemblyQualifiedName, "ConditionDefaultValue");
				GetSerializer(ConditionDefaultValueType).SerializeInternal(AddObject(ConditionDefaultValueObject, 2), WhileStatement.ConditionDefaultValue, ConditionDefaultValueType, References);
				// Statement
				if (WhileStatement.Statement == null)
					Set<object>(Object, 3, null, "Statement");
				else
				{
					ISerializeObject StatementObject = AddObject(Object, 3); 
					string id = string.Empty;
					if (References.Contains(WhileStatement.Statement))
						id = WhileStatement.Statement.ID;
					else
					{
						References.Add(WhileStatement.Statement);
						System.Type StatementType = WhileStatement.Statement.GetType();
						Set(StatementObject, 1, StatementType.AssemblyQualifiedName, "Statement");
						GetSerializer(StatementType).SerializeInternal(AddObject(StatementObject, 2), WhileStatement.Statement, StatementType, References);
					}
					Set(StatementObject, 0, id, "Statement");
				}
				// CompleteStatement
				if (WhileStatement.CompleteStatement == null)
					Set<object>(Object, 1, null, "CompleteStatement");
				else
				{
					ISerializeObject CompleteStatementObject = AddObject(Object, 1); 
					string id = string.Empty;
					if (References.Contains(WhileStatement.CompleteStatement))
						id = WhileStatement.CompleteStatement.ID;
					else
					{
						References.Add(WhileStatement.CompleteStatement);
						System.Type CompleteStatementType = WhileStatement.CompleteStatement.GetType();
						Set(CompleteStatementObject, 1, CompleteStatementType.AssemblyQualifiedName, "CompleteStatement");
						GetSerializer(CompleteStatementType).SerializeInternal(AddObject(CompleteStatementObject, 2), WhileStatement.CompleteStatement, CompleteStatementType, References);
					}
					Set(CompleteStatementObject, 0, id, "CompleteStatement");
				}
				// ID
				Set(Object, 0, WhileStatement.ID, "ID");
			}
		}

		public override T DeserializeInternal<T>(ISerializeData Data, StatementIDTable StatementIDs, ResolverList Resolvers)
		{
			T returnValue = default(T);
			if (Data is ISerializeArray)
			{
				ISerializeArray Array = (ISerializeArray)Data; 
				VisualScriptTool.Language.Statements.Control.WhileStatement[] WhileStatementArray = (VisualScriptTool.Language.Statements.Control.WhileStatement[])System.Array.CreateInstance(Type, Array.Count);
				for (uint i = 0; i < Array.Count; ++i)
				{
					ISerializeObject arrayObj = Get<ISerializeObject>(Array, i);
					System.Type targetType = System.Type.GetType(Get<string>(arrayObj, 1));
					if (arrayObj == null)
					{
						WhileStatementArray[i] = null;
						continue;
					}
					WhileStatementArray[i] = GetSerializer(targetType).DeserializeInternal<VisualScriptTool.Language.Statements.Control.WhileStatement>(Get<ISerializeObject>(arrayObj, 2), StatementIDs, Resolvers); 
				}
				returnValue = (T)(object)WhileStatementArray;
			}
			else
			{
				ISerializeObject Object = (ISerializeObject)Data; 
				VisualScriptTool.Language.Statements.Control.WhileStatement WhileStatement = (VisualScriptTool.Language.Statements.Control.WhileStatement)CreateInstance();
				// Condition
				ISerializeObject ConditionObject = Get<ISerializeObject>(Object, 2, null);
				if (ConditionObject != null)
				{
					ISerializeObject ConditionObjectValue = Get<ISerializeObject>(Object, 2); 
					if (Contains(ConditionObjectValue, 1))
					{
						Serializer ConditionSerializer = GetSerializer(System.Type.GetType(Get<string>(ConditionObjectValue, 1)));
						WhileStatement.Condition = ConditionSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Declaration.VariableStatement>(Get<ISerializeObject>(ConditionObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[WhileStatement.Condition.ID] = WhileStatement.Condition;
					}
					else
					{
						string id = Get<string>(ConditionObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, WhileStatement, WhileStatement.GetType().GetProperty("Condition", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					WhileStatement.Condition = null;
				// ConditionDefaultValue
				ISerializeObject ConditionDefaultValueObject = Get<ISerializeObject>(Object, 4, null);
				if (ConditionDefaultValueObject != null)
				{
					ISerializeObject ConditionDefaultValueObjectValue = Get<ISerializeObject>(Object, 4); 
					Serializer ConditionDefaultValueSerializer = GetSerializer(System.Type.GetType(Get<string>(ConditionDefaultValueObjectValue, 1)));
					WhileStatement.ConditionDefaultValue = ConditionDefaultValueSerializer.DeserializeInternal<VisualScriptTool.Language.AnyDataType>(Get<ISerializeObject>(ConditionDefaultValueObjectValue, 2), StatementIDs, Resolvers);
				}
				// Statement
				ISerializeObject StatementObject = Get<ISerializeObject>(Object, 3, null);
				if (StatementObject != null)
				{
					ISerializeObject StatementObjectValue = Get<ISerializeObject>(Object, 3); 
					if (Contains(StatementObjectValue, 1))
					{
						Serializer StatementSerializer = GetSerializer(System.Type.GetType(Get<string>(StatementObjectValue, 1)));
						WhileStatement.Statement = StatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(StatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[WhileStatement.Statement.ID] = WhileStatement.Statement;
					}
					else
					{
						string id = Get<string>(StatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, WhileStatement, WhileStatement.GetType().GetProperty("Statement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					WhileStatement.Statement = null;
				// CompleteStatement
				ISerializeObject CompleteStatementObject = Get<ISerializeObject>(Object, 1, null);
				if (CompleteStatementObject != null)
				{
					ISerializeObject CompleteStatementObjectValue = Get<ISerializeObject>(Object, 1); 
					if (Contains(CompleteStatementObjectValue, 1))
					{
						Serializer CompleteStatementSerializer = GetSerializer(System.Type.GetType(Get<string>(CompleteStatementObjectValue, 1)));
						WhileStatement.CompleteStatement = CompleteStatementSerializer.DeserializeInternal<VisualScriptTool.Language.Statements.Statement>(Get<ISerializeObject>(CompleteStatementObjectValue, 2), StatementIDs, Resolvers);
						StatementIDs[WhileStatement.CompleteStatement.ID] = WhileStatement.CompleteStatement;
					}
					else
					{
						string id = Get<string>(CompleteStatementObjectValue, 0);
						Resolvers.Add(new ReferenceResolver(id, WhileStatement, WhileStatement.GetType().GetProperty("CompleteStatement", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic)));
					}
				}
				else
					WhileStatement.CompleteStatement = null;
				// ID
				WhileStatement.ID = Get<System.String>(Object, 0, "");
				returnValue = (T)(object)WhileStatement;
			}
			return returnValue;
		}

	}
}
#endif